c=wParam;
		if(submode[mode]==0){
			switch(focus){
				case 1://name
					if((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c==' '){
						if(NumItems==64&&totalLength(ItemName,63)>=663){
							MessageBox(NULL,"You are at the maximum length for item names.\nEither use extended items or shorten another item name.","Error",MB_OK);
							return false;
						}
						if(strlen(ItemName[select[mode]])<21){
							sprintf(ItemName[select[mode]],"%s%c",ItemName[select[mode]],c);
						} else ItemName[select[mode]][20]=c;
					}
					if(c==8&&strlen(ItemName[select[mode]])>0){
						ItemName[select[mode]][strlen(ItemName[select[mode]])-1]=0;
					}
					break;
				case 2://bonus
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][7];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][7]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][7];
						i=i-i%10;
						i/=10;
						Item[select[mode]][7]=i;
					}
					break;
				case 3://price
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][14]*256+Item[select[mode]][15];
						if(i<10000){
							i*=10;
							i+=val;
							Item[select[mode]][15]=i%256;
							Item[select[mode]][14]=(i-Item[select[mode]][15])/256;
						}
					}
					if(c==8){
						i=Item[select[mode]][14]*256+Item[select[mode]][15];
						i=i-i%10;
						i/=10;
						Item[select[mode]][15]=i%256;
						Item[select[mode]][14]=(i-Item[select[mode]][15])/256;
					}
					break;
				case 4://animation
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][8];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][8]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][8];
						i=i-i%10;
						i/=10;
						Item[select[mode]][8]=i;
					}
					break;
				case 5://effect
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][9];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][9]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][9];
						i=i-i%10;
						i/=10;
						Item[select[mode]][9]=i;
					}
					break;
				case 6://range
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][12];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][12]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][12];
						i=i-i%10;
						i/=10;
						Item[select[mode]][12]=i;
					}
					break;
				case 7://offset
					val=c-'0';
					if(c>='a'&&c<='f'){
						val=c-'a'+10;
					}
					if(c>='A'&&c<='F'){
						val=c-'A'+10;
					}
					if(val>=0&&val<16){
						l=ItemNameOffset;
						if(l<524288){
							l*=16;
							l+=val;
							ItemNameOffset=l;
						}
					}
					if(c==8){
						l=ItemNameOffset;
						l=l-l%16;
						l/=16;
						ItemNameOffset=l;
					}
					break;
				case 8://offset
					val=c-'0';
					if(c>='a'&&c<='f'){
						val=c-'a'+10;
					}
					if(c>='A'&&c<='F'){
						val=c-'A'+10;
					}
					if(val>=0&&val<16){
						l=ItemOffset;
						if(l<524288){
							l*=16;
							l+=val;
							ItemOffset=l;
						}
					}
					if(c==8){
						l=ItemOffset;
						l=l-l%16;
						l/=16;
						ItemOffset=l;
					}
					break;
				case 9://effect
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][13];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][13]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][13];
						i=i-i%10;
						i/=10;
						Item[select[mode]][13]=i;
					}
					break;
				case 10://offset
					val=c-'0';
					if(c>='a'&&c<='f'){
						val=c-'a'+10;
					}
					if(c>='A'&&c<='F'){
						val=c-'A'+10;
					}
					if(val>=0&&val<16){
						l=ItemDropOffset;
						if(l<524288){
							l*=16;
							l+=val;
							ItemDropOffset=l;
						}
					}
					if(c==8){
						l=ItemDropOffset;
						l=l-l%16;
						l/=16;
						ItemDropOffset=l;
					}
					break;
				case 11://type
					val=c-'0';
					if(val>=0&&val<10){
						i=ItemType[select[mode]];
						if(i<100){
							i*=10;
							i+=val;
							ItemType[select[mode]]=i;
						}
					}
					if(c==8){
						i=ItemType[select[mode]];
						i=i-i%10;
						i/=10;
						ItemType[select[mode]]=i;
					}
					break;
				case 12://weapon sprite
					val=c-'0';
					if(val>=0&&val<10){
						i=ItemWS[select[mode]];
						if(i<100){
							i*=10;
							i+=val;
							ItemWS[select[mode]]=i;
						}
					}
					if(c==8){
						i=ItemWS[select[mode]];
						i=i-i%10;
						i/=10;
						ItemWS[select[mode]]=i;
					}
					break;
				case 13://?
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][10];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][10]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][10];
						i=i-i%10;
						i/=10;
						Item[select[mode]][10]=i;
					}
					break;
				case 14://?
					val=c-'0';
					if(val>=0&&val<10){
						i=Item[select[mode]][11];
						if(i<100){
							i*=10;
							i+=val;
							Item[select[mode]][11]=i;
						}
					}
					if(c==8){
						i=Item[select[mode]][11];
						i=i-i%10;
						i/=10;
						Item[select[mode]][11]=i;
					}
					break;
			}
}




			if(submode[mode]==1){
				val=c-'0';
				if(focus>0){
					ExtendMapUses=true;
					if(val>=0&&val<10){
						i=MapItem[focus-1];
						if(i<1000){
							i*=10;
							i+=val;
							MapItem[focus-1]=i;
						}
					}
					if(c==8){
						i=MapItem[focus-1];
						i=i-i%10;
						i/=10;
						MapItem[focus-1]=i;
					}
				}
			}

			if(submode[mode]==2){
				val=c-'0';
				if(focus>0&&focus<65){
					if(val>=0&&val<10){
						i=ItemOutfits[focus-1][1];
						if(i<1000){
							i*=10;
							i+=val;
							ItemOutfits[focus-1][1]=i;
						}
					}
					if(c==8){
						i=ItemOutfits[focus-1][1];
						i=i-i%10;
						i/=10;
						ItemOutfits[focus-1][1]=i;
					}
					ItemOutfits[focus-1][1]%=NumItems;
				}
				if(focus>64&&focus<129){
					if(val>=0&&val<10){
						i=ItemOutfits[focus-65][0];
						if(i<1000){
							i*=10;
							i+=val;
							ItemOutfits[focus-65][0]=i;
						}
					}
					if(c==8){
						i=ItemOutfits[focus-65][0];
						i=i-i%10;
						i/=10;
						ItemOutfits[focus-65][0]=i;
					}
					ItemOutfits[focus-65][0]%=30;
				}
				if(focus>128&&focus<193){
					if(val>=0&&val<10){
						i=ItemOutfits[focus-129][2];
						if(i<1000){
							i*=10;
							i+=val;
							ItemOutfits[focus-129][2]=i;
						}
					}
					if(c==8){
						i=ItemOutfits[focus-129][2];
						i=i-i%10;
						i/=10;
						ItemOutfits[focus-129][2]=i;
					}
					ItemOutfits[focus-129][2]%=NumGFX[7];
				}
				if(focus>192){
					if(val>=0&&val<10){
						i=ItemOutfits[focus-193][3];
						if(i<1000){
							i*=10;
							i+=val;
							ItemOutfits[focus-193][3]=i;
						}
					}
					if(c==8){
						i=ItemOutfits[focus-193][3];
						i=i-i%10;
						i/=10;
						ItemOutfits[focus-193][3]=i;
					}
					ItemOutfits[focus-193][3]%=NumGFX[0];
				}
			}