//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SF1Edit.rc
//
#define IDC_MYICON                      2
#define IDD_FONTEDIT_DIALOG             102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_FONTEDIT                    107
#define IDI_SMALL                       108
#define IDC_FONTEDIT                    109
#define MOVEUP                          109
#define IDR_MAINFRAME                   128
#define CHECKOFF                        129
#define CHECKON                         130
#define LEFT2                           131
#define LEFT                            132
#define MID                             133
#define PENCIL                          135
#define PENCILON                        136
#define ERASER                          137
#define ERASERON                        138
#define ONE                             139
#define ONEON                           140
#define TWO                             141
#define TWOON                           142
#define FOUR                            143
#define FOURON                          144
#define PLUS                            145
#define MINUS                           146
#define DOTS                            151
#define RATEON                          152
#define RATE2                           153
#define RATE2ON                         154
#define RATE3                           155
#define RATE3ON                         156
#define RATE4                           157
#define RATE4ON                         158
#define RATE                            159
#define MAGICON                         160
#define MAGIC                           161
#define CHARA                           162
#define CHARAON                         163
#define MONSTER                         170
#define MONSTERON                       171
#define SPELL                           172
#define SPELLON                         173
#define FONT                            174
#define FONTON                          175
#define BATTLE                          176
#define BATTLEON                        177
#define SHOP                            180
#define SHOPON                          181
#define CHESTON                         184
#define CHEST                           185
#define ITEM                            186
#define ITEMON                          187
#define MAP                             190
#define MAPON                           191
#define CLASSI                          194
#define CLASSON                         195
#define NEXT                            198
#define PREV                            199
#define TILE                            201
#define TILEON                          202
#define TILESET1                        208
#define TILESET2                        209
#define TILESET3                        210
#define TILESET4                        211
#define TILESET5                        212
#define TILESET6                        213
#define TILESET7                        214
#define TILESET8                        215
#define TILESET9                        216
#define TILESET10                       217
#define TILESET11                       218
#define TILESET12                       219
#define TILESET13                       220
#define TILESET14                       221
#define TILESET15                       222
#define TILESET16                       223
#define TILESET17                       224
#define TILESET18                       225
#define TILESET19                       226
#define TILESET20                       227
#define TILESET21                       228
#define TILESET22                       229
#define TILESET23                       230
#define TILESET24                       231
#define MECH                            234
#define MECHON                          235
#define EFFECT                          236
#define EFFECTON                        237
#define RANGE                           238
#define RANGEON                         239
#define RANGEASM                        241
#define AREAASM                         243
#define PALETTE                         244
#define PALETTEON                       245
#define TEXTIMG                         246
#define TEXTON                          247
#define SEARCH                          248
#define SPECIAL                         249
#define IDB_BITMAP1                     254
#define IDR_DATA1                       255
#define IDR_DATA2                       256
#define GFXON                           260
#define GFX                             261
#define BG                              263
#define BGON                            264
#define PLATON                          265
#define PLAT                            266
#define PORTRAITON                      267
#define PORTRAIT                        268
#define SPRITEON                        269
#define SPRITE                          270
#define TILESET25                       271
#define TILESET26                       272
#define TILESET28                       273
#define TILESET27                       274
#define TILESET29                       275
#define TILESET30                       276
#define TILESET31                       277
#define TILESET32                       278
#define SCRIPT                          280
#define SCRIPTON                        281
#define DELETEICON                      283
#define ZOOM                            285
#define DOWN                            286
#define UPARROW                         289
#define DOWNARROW                       290
#define ANIMON                          292
#define ANIM                            293
#define AREAS                           296
#define LIST                            297
#define LISTON                          298
#define HIGHLIGHT                       299
#define MOVEDOWN                        301
#define MOVELEFT                        302
#define MOVERIGHT                       303
#define IDB_BITMAP2                     305
#define MOVEADD                         305
#define IDM_OPEN                        32771
#define IDM_LEFT                        32772
#define IDM_RIGHT                       32773
#define IDM_SAVE                        32774
#define IDM_IMPORT                      32775
#define IDM_EXPORT                      32776
#define IDM_EXPAND                      32777
#define ID_FIND                         32778
#define IDM_CHANGE                      32779
#define ID_MODE_CHAR                    32780
#define ID_MODE_LEARN                   32781
#define ID_MODE_ITEM                    32782
#define ID_MODE_ENEMY                   32783
#define ID_MODE_SPELL                   32784
#define ID_MODE_BATTLE                  32785
#define ID_MODE_FONT                    32786
#define ID_MODE_SHOP                    32787
#define ID_MODE_TILE                    32790
#define ID_MODE_MECH                    32791
#define ID_MODE_EFFECT                  32792
#define ID_MODE_RANGE                   32793
#define ID_MODE_PALETTE                 32794
#define ID_MODE_GFX                     32796
#define ID_MODE_SPRITE                  32797
#define ID_MODE_CHEST                   32798
#define ID_MODE_MAP                     32799
#define ID_MODE_SCRIPT                  32800
#define ID_MODE_CLASSF                  32801
#define ID_MODE_CLASSE                  32802
#define ID_MODE_TEXT                    32803
#define ID_MODE_ASSIGN                  32804
#define IDM_HELP                        32805
#define IDM_COPY                        32806
#define IDM_PASTE                       32807
#define IDM_CLEAR                       32808
#define ID_MODE_TBATTLE                 32809
#define ID_MODE_TERRAIN                 32810
#define ID_MODE_ANIM                    32811
#define ID_MODE_DIALOG                  32812
#define ID_MODE_ANIMSET                 32813
#define IDM_LOADCUR                     32814
#define ID_MODE_BATTLEEND               32815
#define ID_DEBUG_PALETTE                32816
#define IDM_RANDOM                      32817
#define ID_DEBUG_CAPPALETTE             32818
#define ID_MODE_BATTLEEXIT              32819
#define ID_MODE_EFFECTOLD               32820
#define ID_MODE_RANGEOLD                32821
#define ID_DEBUG_RESETMAPSPRITEPALETTES 32824
#define ID_DEBUG_GRAPHICSTESTER         32825
#define ID_ANIMATION_EDITENEMYANIMATIONS 32826
#define ID_ANIMATION_ASSIGNFORCEANIMATIONS 32827
#define ID_MODE_EANIM                   32828
#define ID_MODE_EANIMSET                32829
#define ID_DEBUG_FIXEXITS               32830
#define ID_FILE_OPENROMFOLDER           32831
#define IDM_FOLDER                      32832
#define ID_FILE_RECENTFILES             32835
#define IDM_RECENT                      32836
#define IDM_RECENT_FILE1                32837
#define ID_RECENTFILES_1                32837
#define IDM_RECENT_FILE2                32838
#define ID_RECENTFILES_2                32838
#define IDM_RECENT_FILE3                32839
#define ID_RECENTFILES_3                32839
#define IDM_RECENT_FILE4                32840
#define ID_RECENTFILES_4                32840
#define IDM_RECENT_FILE5                32841
#define ID_RECENTFILES_5                32841
#define ID_EDIT_GFXTOCLIPBOARD          32842
#define ID_EDIT_GFXFROMCLIPBOARD        32843
#define IDM_TOCLIPBOARD                 32844
#define IDM_FROMCLIPBOARD               32845
#define ID_EDIT_GFX                     32848
#define IDM_FROMCLIPBOARD_PAL           32849
#define ID_DEBUG_RESETPROMOTEDBATTLESPRITES 32851
#define ID_DEBUG_RESETBS                32852
#define ID_MODE_OBATTLE                 32853
#define ID_SCRIPTING_CHAPTERSTART       32854
#define IDM_MODE_CHAPTERSTART           32855
#define ID_MODE_CHAPTERSTART            32856
#define ID_SCRIPTING_BATTLESTART        32857
#define ID_MODE_BATTLESTART             32858
#define ID_SCRIPTING_WORLDCUTSCENES     32859
#define ID_MODE_WORLD_SCENES            32860
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        306
#define _APS_NEXT_COMMAND_VALUE         32861
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
