			c=wParam;
			if(focus==1&&ShopItems[select[mode]][subfocus]!=-1){
				val=c-'0';
				if(val>=0&&val<10){
					i=ShopItems[select[mode]][subfocus];
					if(i<100){
						i*=10;
						i+=val;
						ShopItems[select[mode]][subfocus]=i;
					}
				}
				if(c==8){
					i=ShopItems[select[mode]][subfocus];
					i=i-i%10;
					i/=10;
					ShopItems[select[mode]][subfocus]=i;
				}
			}